const http=require('http');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {DatabaseSync}=require('node:sqlite');

const ROOT=__dirname;
const PUBLIC=path.join(ROOT,'public');
const DB_PATH=path.join(ROOT,'data','prototype06.db');
if(!fs.existsSync(DB_PATH)) require('./seed.js');
const db=new DatabaseSync(DB_PATH); db.exec('PRAGMA foreign_keys = ON;');

const APP_VERSION='0.6.0-stage5b';
const EVENT_SCHEMA_VERSION='1.1';
const learnerId='l-001', learnerPseudo='P001', sectionId='sec-a', courseId='c-comp101', courseVersionId='cv-comp101-p06';
const id=p=>`${p}-${crypto.randomUUID()}`;
const now=()=>new Date().toISOString();
const wordCount=t=>String(t||'').trim()?String(t).trim().split(/\s+/).length:0;

function send(res,status,body,type='application/json'){
  res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store'});
  res.end(type==='application/json'?JSON.stringify(body):body);
}
function readBody(req){return new Promise((resolve,reject)=>{let data='';req.on('data',c=>data+=c);req.on('end',()=>{try{resolve(data?JSON.parse(data):{})}catch(e){reject(e)}});req.on('error',reject)})}
function sessionFor(){let r=db.prepare(`SELECT * FROM sessions WHERE learner_id=? AND ended_at IS NULL ORDER BY started_at DESC LIMIT 1`).get(learnerId);if(!r){const sid=id('sess');db.prepare(`INSERT INTO sessions VALUES (?,?,?,?,?,?)`).run(sid,learnerId,now(),null,'device-demo',APP_VERSION);r=db.prepare(`SELECT * FROM sessions WHERE session_id=?`).get(sid)}return r}
function nextSeq(j){return Number(db.prepare(`SELECT COALESCE(MAX(sequence_number),0) m FROM events WHERE journey_id=?`).get(j)?.m||0)+1}
function recordEvent({name,journeyId=null,activityInstanceId=null,payload={}}){const eid=id('evt'),sid=sessionFor().session_id,prev=journeyId?db.prepare(`SELECT event_id FROM events WHERE journey_id=? ORDER BY sequence_number DESC LIMIT 1`).get(journeyId):null,t=now();db.prepare(`INSERT INTO events VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(eid,name,EVENT_SCHEMA_VERSION,t,t,learnerPseudo,sid,journeyId,activityInstanceId,journeyId?nextSeq(journeyId):1,'learner_app',APP_VERSION,null,prev?.event_id||null,null,JSON.stringify(payload));return eid}
function activeJourney(){return db.prepare(`SELECT * FROM journeys WHERE learner_id=? AND section_id=? AND week_number=1 AND journey_state='in_progress' ORDER BY started_at DESC LIMIT 1`).get(learnerId,sectionId)}
function lastJourney(){return db.prepare(`SELECT * FROM journeys WHERE learner_id=? AND section_id=? AND week_number=1 ORDER BY started_at DESC LIMIT 1`).get(learnerId,sectionId)}
function activityByOrder(order){return db.prepare(`SELECT a.*,c.title,cv.content_payload FROM activities a JOIN content_versions cv ON a.content_version_id=cv.content_version_id JOIN content c ON cv.content_id=c.content_id WHERE a.course_version_id=? AND a.week_number=1 AND a.activity_order=?`).get(courseVersionId,order)}
function getOrCreateAI(journeyId,activityId){let r=db.prepare(`SELECT * FROM activity_instances WHERE journey_id=? AND activity_id=? ORDER BY attempt_number DESC LIMIT 1`).get(journeyId,activityId);if(!r){const aid=id('ai'),t=now();db.prepare(`INSERT INTO activity_instances VALUES (?,?,?,?,?,?,?,?,?)`).run(aid,activityId,learnerId,journeyId,1,'started',t,t,null);r=db.prepare(`SELECT * FROM activity_instances WHERE activity_instance_id=?`).get(aid)}return r}
function saved(targetType,targetId){return !!db.prepare(`SELECT 1 FROM saved_items WHERE learner_id=? AND target_type=? AND target_id=? AND removed_at IS NULL LIMIT 1`).get(learnerId,targetType,targetId)}
function progress(){return db.prepare(`SELECT * FROM learner_progress WHERE learner_id=? AND section_id=? AND week_number=1`).get(learnerId,sectionId)}
function currentState(){const j=activeJourney();if(!j){const last=lastJourney();return last?.journey_state==='completed'?{state:'completed',journey:last}:{state:'not_started'}}const ai=j.current_activity_instance_id?db.prepare(`SELECT ai.*,a.activity_type,a.activity_order,c.title FROM activity_instances ai JOIN activities a ON ai.activity_id=a.activity_id JOIN content_versions cv ON a.content_version_id=cv.content_version_id JOIN content c ON cv.content_id=c.content_id WHERE ai.activity_instance_id=?`).get(j.current_activity_instance_id):null;return{state:'in_progress',journey:j,currentActivity:ai}}
function home(channel='For You'){const st=currentState();let card;if(st.state==='not_started')card={title:'Writing for Different Audiences',subtitle:'Learn why good writers change how they communicate depending on who they are writing for.',action:'Start',state:'not_started'};else if(st.state==='in_progress')card={title:'Writing for Different Audiences',subtitle:st.currentActivity?`Continue: ${st.currentActivity.title}`:'Continue Week 1',action:'Continue',state:'in_progress'};else card={title:'Writing for Different Audiences',subtitle:'Audience, purpose, critical reading, and your first writing sample are complete.',action:'Review Week 1',state:'completed'};const extras={'Academic English':[ {kicker:'Academic English',title:'Writing a clear email to a professor',subtitle:'See how audience and purpose shape a short academic email.',action:'Open',target_id:'academic-email'} ],'Critical Thinking':[ {kicker:'Critical Thinking',title:'Does frequent technology use mean digital literacy?',subtitle:'Consider the difference between using technology often and using it effectively for learning.',action:'Open',target_id:'critical-digital-literacy'} ],'Prof. Myrick':[ {kicker:'Prof. Myrick',title:'Week 1 note',subtitle:'Clear writing fits the reader and the situation; formal language is not automatically better language.',action:'Open',target_id:'prof-week1-note'} ],'Explore':[ {kicker:'Critical Thinking',title:'Does frequent technology use mean digital literacy?',subtitle:'A short discovery activity connected to Week 1.',action:'Open',target_id:'critical-digital-literacy'} ]};for(const arr of Object.values(extras))for(const item of arr)item.saved=saved('channel_resource',item.target_id);return{learner:{display_name:'Test Learner'},channels:['For You','Composition 101','Academic English','Prof. Myrick','Critical Thinking','+'],bottom_nav:['Home','Explore','Create','Saved','Profile'],priority_card:card,journey_state:st.state,saved:saved('week','week1'),channel,extras:extras[channel]||[]}}

function ensureWritingDraft(ai){let d=db.prepare(`SELECT * FROM writing_drafts WHERE activity_instance_id=?`).get(ai.activity_instance_id);if(!d){const did=id('draft'),t=now();db.prepare(`INSERT INTO writing_drafts VALUES (?,?,?,?,?,?,?,?,?,?)`).run(did,learnerId,ai.activity_instance_id,courseId,sectionId,String(JSON.parse(db.prepare(`SELECT cv.content_payload FROM activities a JOIN content_versions cv ON a.content_version_id=cv.content_version_id WHERE a.activity_id=?`).get(ai.activity_id).content_payload).phase==='baseline'?'Week 1 baseline writing':'Week 1 reading response'),null,'draft',t,t);d=db.prepare(`SELECT * FROM writing_drafts WHERE writing_draft_id=?`).get(did);recordEvent({name:'writing_started',journeyId:ai.journey_id,activityInstanceId:ai.activity_instance_id,payload:{writing_draft_id:did}})}return d}
function writingPayload(ai){const d=ensureWritingDraft(ai);const latest=d.current_version_id?db.prepare(`SELECT * FROM writing_versions WHERE writing_version_id=?`).get(d.current_version_id):null;const f=latest?db.prepare(`SELECT * FROM feedback WHERE target_type='writing_version' AND target_id=? ORDER BY created_at`).all(latest.writing_version_id):[];return{draft:d,latest_version:latest,feedback:f.map(x=>({...x,saved:saved('feedback',x.feedback_id)}))}}
function reflectionPayload(aiId){return db.prepare(`SELECT * FROM reflection_responses WHERE activity_instance_id=? ORDER BY created_at`).all(aiId)}
function activityPayload(aiId){const r=db.prepare(`SELECT ai.*,a.activity_type,a.activity_order,a.activity_id,c.title,cv.content_payload,cv.content_version_id FROM activity_instances ai JOIN activities a ON ai.activity_id=a.activity_id JOIN content_versions cv ON a.content_version_id=cv.content_version_id JOIN content c ON cv.content_id=c.content_id WHERE ai.activity_instance_id=?`).get(aiId);if(!r)return null;const b={activity_instance_id:r.activity_instance_id,activity_id:r.activity_id,activity_type:r.activity_type,title:r.title,state:r.activity_state,content_version_id:r.content_version_id,content:JSON.parse(r.content_payload),saved:saved('content',r.content_version_id)};if(r.activity_type==='learning_stack'){const s=db.prepare(`SELECT * FROM learning_stacks WHERE activity_id=?`).get(r.activity_id),panels=db.prepare(`SELECT * FROM learning_stack_panels WHERE stack_id=? ORDER BY panel_order`).all(s.stack_id).map(p=>({...p,panel_payload:JSON.parse(p.panel_payload)})),pr=db.prepare(`SELECT * FROM stack_progress WHERE activity_instance_id=?`).get(aiId);b.stack={stack_id:s.stack_id,panels,progress:pr?{current_panel_id:pr.current_panel_id,panels_viewed:JSON.parse(pr.panels_viewed),panel_responses:JSON.parse(pr.panel_responses)}:null}}if(r.activity_type==='quick_check'){const q=db.prepare(`SELECT * FROM quick_checks WHERE activity_id=?`).get(r.activity_id);let att=db.prepare(`SELECT * FROM quick_check_attempts WHERE activity_instance_id=? ORDER BY offered_at DESC LIMIT 1`).get(aiId);if(!att){const qaid=id('qca'),t=now();db.prepare(`INSERT INTO quick_check_attempts VALUES (?,?,?,?,?,?,?,?,?,?)`).run(qaid,q.quick_check_id,aiId,learnerId,'offered',t,null,null,null,null);att=db.prepare(`SELECT * FROM quick_check_attempts WHERE quick_check_attempt_id=?`).get(qaid);recordEvent({name:'quick_check_offered',journeyId:r.journey_id,activityInstanceId:aiId,payload:{quick_check_id:q.quick_check_id}})}const questions=db.prepare(`SELECT qi.*,qcq.question_order FROM quick_check_questions qcq JOIN question_items qi ON qi.question_id=qcq.question_id WHERE qcq.quick_check_id=? ORDER BY qcq.question_order`).all(q.quick_check_id).map(x=>({...x,stimulus_payload:x.stimulus_payload?JSON.parse(x.stimulus_payload):null,response_options:x.response_options?JSON.parse(x.response_options):[]}));const responses=db.prepare(`SELECT * FROM response_attempts WHERE quick_check_attempt_id=?`).all(att.quick_check_attempt_id);b.quick_check={...q,attempt:att,questions,responses}}if(r.activity_type==='writing')b.writing=writingPayload(r);if(r.activity_type==='reflection')b.reflection={responses:reflectionPayload(aiId)};return b}
function incrementRequiredIfNeeded(ai){const a=db.prepare(`SELECT requirement_level FROM activities WHERE activity_id=?`).get(ai.activity_id);if(a?.requirement_level!=='required')return;const p=progress();if(p)db.prepare(`UPDATE learner_progress SET required_completed_count=MIN(required_total_count,required_completed_count+1),updated_at=? WHERE learner_id=? AND section_id=? AND week_number=1`).run(now(),learnerId,sectionId)}
function markActivityComplete(ai,eventName='activity_completed'){if(ai.activity_state==='completed'||ai.activity_state==='declined')return;db.prepare(`UPDATE activity_instances SET activity_state='completed',completed_at=?,last_activity_at=? WHERE activity_instance_id=?`).run(now(),now(),ai.activity_instance_id);incrementRequiredIfNeeded(ai);recordEvent({name:eventName,journeyId:ai.journey_id,activityInstanceId:ai.activity_instance_id,payload:{activity_id:ai.activity_id}})}
function nextActivity(journeyId,currentOrder){const next=activityByOrder(currentOrder+1);if(!next)return null;const ai=getOrCreateAI(journeyId,next.activity_id);db.prepare(`UPDATE journeys SET current_activity_instance_id=?,last_activity_at=? WHERE journey_id=?`).run(ai.activity_instance_id,now(),journeyId);return ai}

function supportTemplate(conceptId='concept-audience'){
  if(conceptId==='concept-audience') return [
    {support_type:'alternative_explanation',title:'Think about giving directions',body:'If someone knows the campus well, you might say “It is beside the library.” If they have never visited, you would give more detail. The destination is the same, but the explanation changes because the audience is different.',check:{prompt:'What changes when the audience changes?',options:['Only the topic','The communication choices','Nothing important'],expected:'The communication choices'}},
    {support_type:'comparison',title:'Same idea, different audience',body:'A text to a friend can be short and casual. A message to an instructor usually needs more context and a different tone. Neither style is always better—the useful choice depends on the situation.',check:{prompt:'Which is the best rule?',options:['Always be formal','Always be brief','Match the message to the audience and purpose'],expected:'Match the message to the audience and purpose'}},
    {support_type:'guided_practice',title:'Try one yourself',body:'Imagine you need to ask for an assignment extension. Think about how you would ask a close friend for help versus how you would ask your instructor.',check:{prompt:'For an instructor, which change is most useful?',options:['Add clear context and a respectful request','Use more slang','Remove the reason for the request'],expected:'Add clear context and a respectful request'}}
  ];
  return [{support_type:'alternative_explanation',title:'Let’s try another angle',body:'This support path gives you another representation of the same course idea.',check:{prompt:'Does this make more sense now?',options:['Yes','Not yet'],expected:'Yes'}}];
}
function ensureLearningGap(conceptId,evidenceId){
  let g=db.prepare(`SELECT * FROM learning_gaps WHERE learner_id=? AND concept_id=? AND status IN ('suspected','active','improving') ORDER BY detected_at DESC LIMIT 1`).get(learnerId,conceptId);
  if(!g){const gid=id('gap'),t=now();db.prepare(`INSERT INTO learning_gaps VALUES (?,?,?,?,?,?,?,?,?,?)`).run(gid,learnerId,conceptId,'difficulty_with_core_concept',JSON.stringify([evidenceId]),0.45,'suspected',t,null,null);g=db.prepare(`SELECT * FROM learning_gaps WHERE learning_gap_id=?`).get(gid);recordEvent({name:'learning_gap_created',journeyId:activeJourney()?.journey_id||null,payload:{learning_gap_id:gid,concept_id:conceptId,status:'suspected'}})}
  else {const ev=JSON.parse(g.evidence_ids||'[]');if(!ev.includes(evidenceId))ev.push(evidenceId);const conf=Math.min(0.9,Number(g.confidence||0)+0.2),status=conf>=0.65?'active':g.status;db.prepare(`UPDATE learning_gaps SET evidence_ids=?,confidence=?,status=? WHERE learning_gap_id=?`).run(JSON.stringify(ev),conf,status,g.learning_gap_id);recordEvent({name:'learning_gap_updated',journeyId:activeJourney()?.journey_id||null,payload:{learning_gap_id:g.learning_gap_id,concept_id:conceptId,status,confidence:conf}});g=db.prepare(`SELECT * FROM learning_gaps WHERE learning_gap_id=?`).get(g.learning_gap_id)}
  return g;
}
function supportPayload(pathId){
  const sp=db.prepare(`SELECT * FROM support_paths WHERE support_path_id=? AND learner_id=?`).get(pathId,learnerId);if(!sp)return null;
  const units=db.prepare(`SELECT * FROM support_units WHERE support_path_id=? ORDER BY unit_order`).all(pathId).map(u=>({...u,content_payload:JSON.parse(u.content_payload)}));
  return {path:sp,units,current_unit:units.find(u=>u.unit_order===sp.current_step)||units[units.length-1],escalation_options:['Ask the Class','Ask Prof. Myrick','Save for Later']};
}
function createSupportPath(aiId,trigger='learner_requested',conceptId='concept-audience'){
  const ai=db.prepare(`SELECT * FROM activity_instances WHERE activity_instance_id=?`).get(aiId);if(!ai)return null;
  const sid=id('support'),t=now();db.prepare(`INSERT INTO support_paths VALUES (?,?,?,?,?,?,?,?,?,?,?)`).run(sid,learnerId,ai.journey_id,aiId,conceptId,trigger,'active',1,t,null,null);
  const templates=supportTemplate(conceptId);for(let i=0;i<templates.length;i++){const uid=id('su');db.prepare(`INSERT INTO support_units VALUES (?,?,?,?,?,?,?,?,?,?)`).run(uid,sid,i+1,templates[i].support_type,JSON.stringify(templates[i]),'AI_generated_grounded_prototype','approved',null,null,null)}
  recordEvent({name:'ai_support_requested',journeyId:ai.journey_id,activityInstanceId:aiId,payload:{support_path_id:sid,concept_id:conceptId,trigger}});recordEvent({name:'support_path_started',journeyId:ai.journey_id,activityInstanceId:aiId,payload:{support_path_id:sid,concept_id:conceptId}});const first=db.prepare(`SELECT * FROM support_units WHERE support_path_id=? AND unit_order=1`).get(sid);if(first){db.prepare(`UPDATE support_units SET presented_at=? WHERE support_unit_id=?`).run(t,first.support_unit_id);recordEvent({name:'support_unit_presented',journeyId:ai.journey_id,activityInstanceId:aiId,payload:{support_path_id:sid,support_unit_id:first.support_unit_id,support_type:first.support_type,step:1}});recordEvent({name:'understanding_check_presented',journeyId:ai.journey_id,activityInstanceId:aiId,payload:{support_path_id:sid,step:1}})}return supportPayload(sid)
}

function feedbackFor(text){const wc=wordCount(text);const strength=wc>=120?'You developed your main idea with useful detail.':'You established a clear starting point and stayed with one main idea.';const priority=wc<100?'Add more explanation so the reader can see how your example supports your main point.':'Check that each example is followed by enough explanation for the reader to understand why it matters.';return{strength,priority}}

const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');
  if(url.pathname==='/api/health')return send(res,200,{ok:true,version:APP_VERSION});
  if(url.pathname==='/api/me/home'&&req.method==='GET')return send(res,200,home(url.searchParams.get('channel')||'For You'));
  if(url.pathname==='/api/journeys/start'&&req.method==='POST'){let j=activeJourney();if(!j){const last=lastJourney();if(last?.journey_state==='completed')return send(res,409,{error:'Week 1 already completed'});const jid=id('journey'),t=now();db.prepare(`INSERT INTO journeys VALUES (?,?,?,?,?,?,?,?,?,?,?)`).run(jid,learnerId,courseId,sectionId,courseVersionId,1,'in_progress',null,t,t,null);db.prepare(`INSERT OR REPLACE INTO learner_progress VALUES (?,?,?,?,?,?,?,?,?)`).run(id('lp'),learnerId,courseId,sectionId,1,'in_progress',0,5,t);j=db.prepare(`SELECT * FROM journeys WHERE journey_id=?`).get(jid);recordEvent({name:'journey_started',journeyId:jid,payload:{course_id:courseId,section_id:sectionId,week_number:1}})}const first=activityByOrder(2),ai=j.current_activity_instance_id?db.prepare(`SELECT * FROM activity_instances WHERE activity_instance_id=?`).get(j.current_activity_instance_id):getOrCreateAI(j.journey_id,first.activity_id);db.prepare(`UPDATE journeys SET current_activity_instance_id=?,last_activity_at=? WHERE journey_id=?`).run(ai.activity_instance_id,now(),j.journey_id);recordEvent({name:'priority_card_opened',journeyId:j.journey_id,activityInstanceId:ai.activity_instance_id,payload:{activity_id:ai.activity_id}});if(ai.activity_id===first.activity_id&&ai.activity_state==='started')recordEvent({name:'learning_stack_started',journeyId:j.journey_id,activityInstanceId:ai.activity_instance_id,payload:{activity_id:ai.activity_id}});return send(res,200,{journey_id:j.journey_id,current_activity_instance_id:ai.activity_instance_id})}
  if(url.pathname==='/api/journeys/current'&&req.method==='GET'){const j=activeJourney();return send(res,200,j?{journey:j,activity:activityPayload(j.current_activity_instance_id)}:{journey:null})}

  if(url.pathname==='/api/support/events'&&req.method==='POST'){
    const b=await readBody(req);
    const allowed=['support_hub_opened','support_unit_presented','understanding_check_response','external_resource_opened','contextual_question_submitted','support_resolved'];
    const types={alternative_explanation:'AI_generated_grounded_prototype',worked_example:'authored_prototype',comprehension_check:'authored_prototype',external_resource:'curated_external_resource',contextual_question:'local_excerpt_rule'};
    if(!allowed.includes(b.event)||(b.support_type!=null&&!types[b.support_type]))return send(res,400,{error:'Invalid support event'});
    const ai=db.prepare('SELECT * FROM activity_instances WHERE activity_instance_id=? AND learner_id=?').get(b.activity_instance_id,learnerId);
    if(!ai)return send(res,404,{error:'Activity not found'});
    const validId=x=>typeof x==='string'&&/^[a-f0-9-]{36}$/.test(x);
    if(!validId(b.support_path_id)||!validId(b.event_id))return send(res,400,{error:'Invalid support identifiers'});
    if(db.prepare("SELECT event_id FROM events WHERE json_extract(payload,'$.client_event_id')=?").get(b.event_id))return send(res,200,{ok:true});
    const sid='hub-'+b.support_path_id,uid=validId(b.support_unit_id)?'hub-unit-'+b.support_unit_id:null,t=now();
    const existing=db.prepare('SELECT * FROM support_paths WHERE support_path_id=?').get(sid);
    if(existing&&existing.originating_activity_instance_id!==ai.activity_instance_id)return send(res,400,{error:'Support activity mismatch'});
    if(!existing){
      db.prepare('INSERT INTO support_paths VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(sid,learnerId,ai.journey_id,ai.activity_instance_id,null,'learner_requested','active',1,t,null,null);
      recordEvent({name:'support_path_started',journeyId:ai.journey_id,activityInstanceId:ai.activity_instance_id,payload:{support_path_id:sid,entry_point:b.layer}});
    }
    if(uid&&b.support_type&&b.support_type!=='contextual_question'&&!db.prepare('SELECT support_unit_id FROM support_units WHERE support_unit_id=?').get(uid)){
      const step=db.prepare('SELECT COUNT(*) n FROM support_units WHERE support_path_id=?').get(sid).n+1;
      db.prepare('INSERT INTO support_units VALUES (?,?,?,?,?,?,?,?,?,?)').run(uid,sid,step,b.support_type,JSON.stringify({title:String(b.content?.title||'').slice(0,200),body:String(b.content?.body||'').slice(0,4000)}),types[b.support_type],'approved',t,null,null);
      db.prepare('UPDATE support_paths SET current_step=? WHERE support_path_id=?').run(step,sid);
    }
    if(uid&&['understanding_check_response','support_resolved'].includes(b.event))db.prepare('UPDATE support_units SET completed_at=?,learner_response=? WHERE support_unit_id=? AND support_path_id=?').run(t,b.event==='support_resolved'?'got_it':JSON.stringify({correct:!!b.correct}),uid,sid);
    if(b.event==='support_resolved')db.prepare("UPDATE support_paths SET support_state='resolved',resolved_at=?,resolution_type='learner_reported_understanding' WHERE support_path_id=?").run(t,sid);
    recordEvent({name:b.event,journeyId:ai.journey_id,activityInstanceId:ai.activity_instance_id,payload:{client_event_id:b.event_id,support_path_id:sid,support_unit_id:uid,support_type:b.support_type||null,provenance_type:types[b.support_type]||null,layer:b.layer,panel_index:b.panel_index,correct:b.correct,question:String(b.question||'').slice(0,600),answer:String(b.answer||'').slice(0,4000)}});
    return send(res,200,{ok:true});
  }
  if(url.pathname==='/api/support/start'&&req.method==='POST'){const b=await readBody(req),p=createSupportPath(String(b.activity_instance_id||''),String(b.trigger_type||'learner_requested'),String(b.concept_id||'concept-audience'));return p?send(res,200,p):send(res,404,{error:'Activity not found'})}
  const sget=url.pathname.match(/^\/api\/support\/([^/]+)$/);if(sget&&req.method==='GET'){const p=supportPayload(sget[1]);return p?send(res,200,p):send(res,404,{error:'Support path not found'})}
  const sact=url.pathname.match(/^\/api\/support\/([^/]+)\/respond$/);if(sact&&req.method==='POST'){const b=await readBody(req),sp=db.prepare(`SELECT * FROM support_paths WHERE support_path_id=? AND learner_id=?`).get(sact[1],learnerId);if(!sp)return send(res,404,{error:'Support path not found'});const ai=db.prepare(`SELECT * FROM activity_instances WHERE activity_instance_id=?`).get(sp.originating_activity_instance_id),t=now(),resp=String(b.response||'');const unit=db.prepare(`SELECT * FROM support_units WHERE support_path_id=? AND unit_order=?`).get(sp.support_path_id,sp.current_step);if(unit)db.prepare(`UPDATE support_units SET completed_at=?,learner_response=? WHERE support_unit_id=?`).run(t,resp,unit.support_unit_id);recordEvent({name:'understanding_check_response',journeyId:sp.journey_id,activityInstanceId:sp.originating_activity_instance_id,payload:{support_path_id:sp.support_path_id,step:sp.current_step,response:resp}});if(resp==='got_it'){db.prepare(`UPDATE support_paths SET support_state='resolved',resolved_at=?,resolution_type='learner_reported_understanding' WHERE support_path_id=?`).run(t,sp.support_path_id);recordEvent({name:'support_resolved',journeyId:sp.journey_id,activityInstanceId:sp.originating_activity_instance_id,payload:{support_path_id:sp.support_path_id,step:sp.current_step}});return send(res,200,supportPayload(sp.support_path_id))}if(resp==='still_stuck'&&sp.current_step>=3){db.prepare(`UPDATE support_paths SET support_state='escalated',resolved_at=?,resolution_type='human_escalation' WHERE support_path_id=?`).run(t,sp.support_path_id);recordEvent({name:'support_escalated',journeyId:sp.journey_id,activityInstanceId:sp.originating_activity_instance_id,payload:{support_path_id:sp.support_path_id}});return send(res,200,supportPayload(sp.support_path_id))}const next=Math.min(3,sp.current_step+1);db.prepare(`UPDATE support_paths SET current_step=? WHERE support_path_id=?`).run(next,sp.support_path_id);const nu=db.prepare(`SELECT * FROM support_units WHERE support_path_id=? AND unit_order=?`).get(sp.support_path_id,next);if(nu&&!nu.presented_at){db.prepare(`UPDATE support_units SET presented_at=? WHERE support_unit_id=?`).run(t,nu.support_unit_id);recordEvent({name:'support_unit_presented',journeyId:sp.journey_id,activityInstanceId:sp.originating_activity_instance_id,payload:{support_path_id:sp.support_path_id,support_unit_id:nu.support_unit_id,support_type:nu.support_type,step:next}});recordEvent({name:'understanding_check_presented',journeyId:sp.journey_id,activityInstanceId:sp.originating_activity_instance_id,payload:{support_path_id:sp.support_path_id,step:next}})}recordEvent({name:'alternate_explanation_requested',journeyId:sp.journey_id,activityInstanceId:sp.originating_activity_instance_id,payload:{support_path_id:sp.support_path_id,next_step:next,response:resp}});return send(res,200,supportPayload(sp.support_path_id))}
  const sesc=url.pathname.match(/^\/api\/support\/([^/]+)\/escalate$/);if(sesc&&req.method==='POST'){const b=await readBody(req),sp=db.prepare(`SELECT * FROM support_paths WHERE support_path_id=? AND learner_id=?`).get(sesc[1],learnerId);if(!sp)return send(res,404,{error:'Support path not found'});const choice=String(b.choice||'Save for Later'),t=now(),state=choice==='Save for Later'?'saved_for_later':'escalated';db.prepare(`UPDATE support_paths SET support_state=?,resolved_at=?,resolution_type=? WHERE support_path_id=?`).run(state,t,choice,sp.support_path_id);recordEvent({name:'support_escalated',journeyId:sp.journey_id,activityInstanceId:sp.originating_activity_instance_id,payload:{support_path_id:sp.support_path_id,choice}});return send(res,200,{ok:true,choice,state})}

  const act=url.pathname.match(/^\/api\/activities\/([^/]+)$/);if(act&&req.method==='GET'){const p=activityPayload(act[1]);return p?send(res,200,p):send(res,404,{error:'Activity not found'})}
  const panel=url.pathname.match(/^\/api\/activities\/([^/]+)\/panel$/);if(panel&&req.method==='POST'){const body=await readBody(req),aiId=panel[1],ai=db.prepare(`SELECT * FROM activity_instances WHERE activity_instance_id=?`).get(aiId);if(!ai)return send(res,404,{error:'Activity instance not found'});const pn=db.prepare(`SELECT * FROM learning_stack_panels WHERE panel_id=?`).get(body.panel_id);let pr=db.prepare(`SELECT * FROM stack_progress WHERE activity_instance_id=?`).get(aiId),viewed=pr?JSON.parse(pr.panels_viewed):[],responses=pr?JSON.parse(pr.panel_responses):{},rev=viewed.includes(body.panel_id);if(!rev)viewed.push(body.panel_id);if(body.response!==undefined)responses[body.panel_id]=body.response;if(pr)db.prepare(`UPDATE stack_progress SET current_panel_id=?,panels_viewed=?,panel_responses=?,last_updated_at=? WHERE activity_instance_id=?`).run(body.panel_id,JSON.stringify(viewed),JSON.stringify(responses),now(),aiId);else db.prepare(`INSERT INTO stack_progress VALUES (?,?,?,?,?)`).run(aiId,body.panel_id,JSON.stringify(viewed),JSON.stringify(responses),now());db.prepare(`UPDATE activity_instances SET activity_state='in_progress',last_activity_at=? WHERE activity_instance_id=?`).run(now(),aiId);db.prepare(`UPDATE journeys SET current_activity_instance_id=?,last_activity_at=? WHERE journey_id=?`).run(aiId,now(),ai.journey_id);recordEvent({name:rev?'stack_panel_revisited':'stack_panel_viewed',journeyId:ai.journey_id,activityInstanceId:aiId,payload:{panel_id:body.panel_id,panel_order:pn.panel_order}});if(body.response!==undefined)recordEvent({name:'stack_panel_response',journeyId:ai.journey_id,activityInstanceId:aiId,payload:{panel_id:body.panel_id,response:body.response}});return send(res,200,{ok:true})}
  const complete=url.pathname.match(/^\/api\/activities\/([^/]+)\/complete$/);if(complete&&req.method==='POST'){const ai=db.prepare(`SELECT ai.*,a.activity_order,a.activity_type FROM activity_instances ai JOIN activities a ON ai.activity_id=a.activity_id WHERE ai.activity_instance_id=?`).get(complete[1]);if(!ai)return send(res,404,{error:'Activity instance not found'});markActivityComplete(ai,ai.activity_type==='reading'?'reading_completed':ai.activity_type==='learning_stack'?'learning_stack_completed':'activity_completed');const n=nextActivity(ai.journey_id,ai.activity_order);return send(res,200,{ok:true,next_activity_instance_id:n?.activity_instance_id||null})}
  const qcAccept=url.pathname.match(/^\/api\/quick-checks\/([^/]+)\/(accept|decline)$/);if(qcAccept&&req.method==='POST'){const aiId=qcAccept[1],action=qcAccept[2],ai=db.prepare(`SELECT * FROM activity_instances WHERE activity_instance_id=?`).get(aiId),q=db.prepare(`SELECT qc.* FROM quick_checks qc JOIN activities a ON qc.activity_id=a.activity_id WHERE a.activity_id=?`).get(ai.activity_id),att=db.prepare(`SELECT * FROM quick_check_attempts WHERE activity_instance_id=? ORDER BY offered_at DESC LIMIT 1`).get(aiId),t=now();if(action==='accept'){db.prepare(`UPDATE quick_check_attempts SET attempt_state='in_progress',accepted_at=?,started_at=? WHERE quick_check_attempt_id=?`).run(t,t,att.quick_check_attempt_id);db.prepare(`UPDATE activity_instances SET activity_state='in_progress',last_activity_at=? WHERE activity_instance_id=?`).run(t,aiId);recordEvent({name:'quick_check_accepted',journeyId:ai.journey_id,activityInstanceId:aiId,payload:{quick_check_id:q.quick_check_id}});return send(res,200,{ok:true})}db.prepare(`UPDATE quick_check_attempts SET attempt_state='declined',declined_at=? WHERE quick_check_attempt_id=?`).run(t,att.quick_check_attempt_id);db.prepare(`UPDATE activity_instances SET activity_state='declined',completed_at=?,last_activity_at=? WHERE activity_instance_id=?`).run(t,t,aiId);recordEvent({name:'quick_check_declined',journeyId:ai.journey_id,activityInstanceId:aiId,payload:{quick_check_id:q.quick_check_id}});const arow=db.prepare(`SELECT activity_order FROM activities WHERE activity_id=?`).get(ai.activity_id),n=nextActivity(ai.journey_id,arow.activity_order);return send(res,200,{ok:true,next_activity_instance_id:n?.activity_instance_id||null})}
  const resp=url.pathname.match(/^\/api\/quick-checks\/([^/]+)\/responses$/);if(resp&&req.method==='POST'){const aiId=resp[1],body=await readBody(req),ai=db.prepare(`SELECT * FROM activity_instances WHERE activity_instance_id=?`).get(aiId),att=db.prepare(`SELECT * FROM quick_check_attempts WHERE activity_instance_id=? ORDER BY offered_at DESC LIMIT 1`).get(aiId),q=db.prepare(`SELECT * FROM question_items WHERE question_id=?`).get(body.question_id);if(!q)return send(res,400,{error:'Question not found'});const correct=String(body.response)===String(q.expected_response),rid=id('resp'),t=now();db.prepare(`INSERT INTO response_attempts VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).run(rid,q.question_id,att.quick_check_attempt_id,aiId,learnerId,String(body.response),correct?1:0,1,body.started_at||t,t,body.response_time_ms||null,1);recordEvent({name:'response_submitted',journeyId:ai.journey_id,activityInstanceId:aiId,payload:{question_id:q.question_id,response_attempt_id:rid,correct}});recordEvent({name:'feedback_presented',journeyId:ai.journey_id,activityInstanceId:aiId,payload:{question_id:q.question_id,correct}});if(!correct&&q.concept_id)ensureLearningGap(q.concept_id,rid);const required=db.prepare(`SELECT COUNT(*) c FROM quick_check_questions WHERE quick_check_id=? AND required=1`).get(att.quick_check_id).c,answered=db.prepare(`SELECT COUNT(DISTINCT question_id) c FROM response_attempts WHERE quick_check_attempt_id=?`).get(att.quick_check_attempt_id).c;let nextId=null,done=answered>=required;if(done){db.prepare(`UPDATE quick_check_attempts SET attempt_state='completed',completed_at=? WHERE quick_check_attempt_id=?`).run(t,att.quick_check_attempt_id);db.prepare(`UPDATE activity_instances SET activity_state='completed',completed_at=?,last_activity_at=? WHERE activity_instance_id=?`).run(t,t,aiId);recordEvent({name:'quick_check_completed',journeyId:ai.journey_id,activityInstanceId:aiId,payload:{quick_check_id:att.quick_check_id}});const arow=db.prepare(`SELECT activity_order FROM activities WHERE activity_id=?`).get(ai.activity_id);nextId=nextActivity(ai.journey_id,arow.activity_order)?.activity_instance_id||null}return send(res,200,{ok:true,correct,feedback:correct?q.feedback_correct:q.feedback_incorrect,completed:done,next_activity_instance_id:nextId})}
  const readingStart=url.pathname.match(/^\/api\/activities\/([^/]+)\/reading-start$/);if(readingStart&&req.method==='POST'){const ai=db.prepare(`SELECT * FROM activity_instances WHERE activity_instance_id=?`).get(readingStart[1]);db.prepare(`UPDATE activity_instances SET activity_state='in_progress',last_activity_at=? WHERE activity_instance_id=?`).run(now(),ai.activity_instance_id);recordEvent({name:'reading_started',journeyId:ai.journey_id,activityInstanceId:ai.activity_instance_id,payload:{activity_id:ai.activity_id}});return send(res,200,{ok:true})}
  const wsave=url.pathname.match(/^\/api\/writing\/([^/]+)\/save$/);if(wsave&&req.method==='POST'){const body=await readBody(req),ai=db.prepare(`SELECT * FROM activity_instances WHERE activity_instance_id=?`).get(wsave[1]);if(!ai)return send(res,404,{error:'Activity not found'});const d=ensureWritingDraft(ai),vnum=Number(db.prepare(`SELECT COALESCE(MAX(version_number),0) m FROM writing_versions WHERE writing_draft_id=?`).get(d.writing_draft_id).m)+1,vid=id('wv'),t=now();db.prepare(`INSERT INTO writing_versions VALUES (?,?,?,?,?,?,?,?,?)`).run(vid,d.writing_draft_id,vnum,String(body.text||''),String(body.source_mode||'typed'),wordCount(body.text),'draft',t,null);db.prepare(`UPDATE writing_drafts SET current_version_id=?,draft_status='draft',updated_at=? WHERE writing_draft_id=?`).run(vid,t,d.writing_draft_id);db.prepare(`UPDATE activity_instances SET activity_state='in_progress',last_activity_at=? WHERE activity_instance_id=?`).run(t,ai.activity_instance_id);recordEvent({name:'draft_saved',journeyId:ai.journey_id,activityInstanceId:ai.activity_instance_id,payload:{writing_draft_id:d.writing_draft_id,writing_version_id:vid,word_count:wordCount(body.text),source_mode:String(body.source_mode||'typed')}});return send(res,200,{ok:true,writing_version_id:vid})}
  const wsubmit=url.pathname.match(/^\/api\/writing\/([^/]+)\/submit$/);if(wsubmit&&req.method==='POST'){const body=await readBody(req),ai=db.prepare(`SELECT * FROM activity_instances WHERE activity_instance_id=?`).get(wsubmit[1]);if(!ai)return send(res,404,{error:'Activity not found'});const d=ensureWritingDraft(ai),vnum=Number(db.prepare(`SELECT COALESCE(MAX(version_number),0) m FROM writing_versions WHERE writing_draft_id=?`).get(d.writing_draft_id).m)+1,vid=id('wv'),t=now(),text=String(body.text||'');db.prepare(`INSERT INTO writing_versions VALUES (?,?,?,?,?,?,?,?,?)`).run(vid,d.writing_draft_id,vnum,text,String(body.source_mode||'typed'),wordCount(text),'submitted',t,t);db.prepare(`UPDATE writing_drafts SET current_version_id=?,draft_status='submitted',updated_at=? WHERE writing_draft_id=?`).run(vid,t,d.writing_draft_id);db.prepare(`UPDATE activity_instances SET activity_state='in_progress',last_activity_at=? WHERE activity_instance_id=?`).run(t,ai.activity_instance_id);if(body.baseline_confidence){db.prepare(`INSERT OR REPLACE INTO reflection_responses VALUES (?,?,?,?,?,?,?,?)`).run(id('rr'),learnerId,ai.activity_instance_id,'baseline_writing_confidence','selection',null,String(body.baseline_confidence),t)}recordEvent({name:'writing_submitted',journeyId:ai.journey_id,activityInstanceId:ai.activity_instance_id,payload:{writing_draft_id:d.writing_draft_id,writing_version_id:vid,word_count:wordCount(text),learner_submission_timestamp:t,source_mode:String(body.source_mode||'typed'),baseline_confidence:body.baseline_confidence||null}});const payload=JSON.parse(db.prepare(`SELECT cv.content_payload FROM activities a JOIN content_versions cv ON a.content_version_id=cv.content_version_id WHERE a.activity_id=?`).get(ai.activity_id).content_payload);if(payload.feedback_mode==='none')return send(res,200,{ok:true,submitted:true,feedback:[],feedback_mode:'none'});const fb=feedbackFor(text),f1=id('fb'),f2=id('fb');db.prepare(`INSERT INTO feedback VALUES (?,?,?,?,?,?,?,?,?,?)`).run(f1,learnerId,'writing_version',vid,'system_rule','strength',fb.strength,t,t,0);db.prepare(`INSERT INTO feedback VALUES (?,?,?,?,?,?,?,?,?,?)`).run(f2,learnerId,'writing_version',vid,'system_rule','priority_improvement',fb.priority,t,t,0);recordEvent({name:'feedback_generated',journeyId:ai.journey_id,activityInstanceId:ai.activity_instance_id,payload:{target_id:vid,source:'system_rule'}});recordEvent({name:'feedback_presented',journeyId:ai.journey_id,activityInstanceId:ai.activity_instance_id,payload:{target_id:vid,feedback_ids:[f1,f2]}});return send(res,200,{ok:true,submitted:true,feedback:[{feedback_id:f1,feedback_category:'strength',feedback_text:fb.strength},{feedback_id:f2,feedback_category:'priority_improvement',feedback_text:fb.priority}]})}
  const wcontinue=url.pathname.match(/^\/api\/writing\/([^/]+)\/continue$/);if(wcontinue&&req.method==='POST'){const ai=db.prepare(`SELECT ai.*,a.activity_order FROM activity_instances ai JOIN activities a ON ai.activity_id=a.activity_id WHERE ai.activity_instance_id=?`).get(wcontinue[1]);if(!ai)return send(res,404,{error:'Activity not found'});markActivityComplete(ai,'writing_activity_completed');const n=nextActivity(ai.journey_id,ai.activity_order);return send(res,200,{ok:true,next_activity_instance_id:n?.activity_instance_id||null})}
  const refl=url.pathname.match(/^\/api\/reflections\/([^/]+)\/submit$/);if(refl&&req.method==='POST'){const body=await readBody(req),ai=db.prepare(`SELECT ai.*,a.activity_order FROM activity_instances ai JOIN activities a ON ai.activity_id=a.activity_id WHERE ai.activity_instance_id=?`).get(refl[1]);if(!ai)return send(res,404,{error:'Activity not found'});const t=now();for(const [promptId,responseText] of Object.entries(body.responses||{})){const responseMode=String(body.responseModes?.[promptId]||'text');db.prepare(`INSERT OR REPLACE INTO reflection_responses VALUES (?,?,?,?,?,?,?,?)`).run(id('rr'),learnerId,ai.activity_instance_id,promptId,responseMode,String(responseText||''),null,t);recordEvent({name:'reflection_response_submitted',journeyId:ai.journey_id,activityInstanceId:ai.activity_instance_id,payload:{prompt_id:promptId,response_mode:responseMode}})}if(body.confidence){db.prepare(`INSERT OR REPLACE INTO reflection_responses VALUES (?,?,?,?,?,?,?,?)`).run(id('rr'),learnerId,ai.activity_instance_id,'confidence','selection',null,String(body.confidence),t);recordEvent({name:'confidence_submitted',journeyId:ai.journey_id,activityInstanceId:ai.activity_instance_id,payload:{confidence:body.confidence}})}markActivityComplete(ai,'reflection_completed');const n=nextActivity(ai.journey_id,ai.activity_order);return send(res,200,{ok:true,next_activity_instance_id:n?.activity_instance_id||null})}
  if(url.pathname==='/api/week1/complete'&&req.method==='POST'){const body=await readBody(req),j=activeJourney();if(!j)return send(res,400,{error:'No active journey'});const ai=db.prepare(`SELECT ai.*,a.activity_order FROM activity_instances ai JOIN activities a ON ai.activity_id=a.activity_id WHERE ai.activity_instance_id=?`).get(j.current_activity_instance_id);if(ai)markActivityComplete(ai,'completion_card_acknowledged');const t=now();db.prepare(`UPDATE journeys SET journey_state='completed',completed_at=?,last_activity_at=? WHERE journey_id=?`).run(t,t,j.journey_id);db.prepare(`UPDATE learner_progress SET progress_state='completed',required_completed_count=required_total_count,updated_at=? WHERE learner_id=? AND section_id=? AND week_number=1`).run(t,learnerId,sectionId);recordEvent({name:'week_completed',journeyId:j.journey_id,activityInstanceId:ai?.activity_instance_id||null,payload:{week_number:1}});recordEvent({name:body.action==='explore'?'keep_exploring_selected':'done_for_now_selected',journeyId:j.journey_id,activityInstanceId:ai?.activity_instance_id||null,payload:{week_number:1}});return send(res,200,{ok:true,completed:true,action:body.action||'done'})}
  if(url.pathname==='/api/saved'&&req.method==='POST'){const b=await readBody(req),existing=db.prepare(`SELECT * FROM saved_items WHERE learner_id=? AND target_type=? AND target_id=? AND removed_at IS NULL`).get(learnerId,b.target_type,b.target_id);if(existing)return send(res,200,{saved:true,id:existing.saved_item_id});const sid=id('saved');db.prepare(`INSERT INTO saved_items VALUES (?,?,?,?,?,?,?)`).run(sid,learnerId,b.target_type,b.target_id,now(),null,b.offline_available?1:0);recordEvent({name:'item_saved',journeyId:activeJourney()?.journey_id||lastJourney()?.journey_id||null,payload:{target_type:b.target_type,target_id:b.target_id}});return send(res,200,{saved:true,id:sid})}
  const unsave=url.pathname.match(/^\/api\/saved\/([^/]+)\/([^/]+)$/);if(unsave&&req.method==='DELETE'){db.prepare(`UPDATE saved_items SET removed_at=? WHERE learner_id=? AND target_type=? AND target_id=? AND removed_at IS NULL`).run(now(),learnerId,unsave[1],unsave[2]);return send(res,200,{saved:false})}
  if(url.pathname==='/api/me/saved'&&req.method==='GET'){const rows=db.prepare(`SELECT * FROM saved_items WHERE learner_id=? AND removed_at IS NULL ORDER BY saved_at DESC`).all(learnerId);return send(res,200,{items:rows})}

  if(url.pathname==='/api/review/week1'&&req.method==='GET'){
    const j=lastJourney();
    if(!j||j.journey_state!=='completed')return send(res,404,{error:'Completed Week 1 not found'});
    const rows=db.prepare(`SELECT ai.activity_instance_id,a.activity_order,a.activity_type,c.title FROM activity_instances ai JOIN activities a ON ai.activity_id=a.activity_id JOIN content_versions cv ON a.content_version_id=cv.content_version_id JOIN content c ON cv.content_id=c.content_id WHERE ai.journey_id=? AND a.week_number=1 ORDER BY a.activity_order`).all(j.journey_id);
    const activities=rows.filter(r=>!['priority','completion'].includes(r.activity_type)).map(r=>({order:r.activity_order,type:r.activity_type,title:r.title,payload:activityPayload(r.activity_instance_id)}));
    return send(res,200,{journey_id:j.journey_id,course:'Composition 101',week:1,activities});
  }
  if(url.pathname==='/api/me/learning'&&req.method==='GET'){const d=db.prepare(`SELECT wd.draft_status,wv.word_count,wv.submitted_at FROM writing_drafts wd LEFT JOIN writing_versions wv ON wd.current_version_id=wv.writing_version_id WHERE wd.learner_id=? ORDER BY wd.updated_at DESC LIMIT 1`).get(learnerId);return send(res,200,{course:'Composition 101',week1:progress()||{progress_state:'not_started'},writing:d||null,concepts:[{name:'Audience',state:'In Progress'},{name:'Purpose',state:'In Progress'},{name:'Rhetorical Context',state:'In Progress'}]})}
  if(url.pathname==='/api/faculty/section-a'&&req.method==='GET'){const learners=db.prepare(`SELECT lp.*,u.display_name FROM learner_progress lp JOIN learners l ON lp.learner_id=l.learner_id JOIN users u ON l.user_id=u.user_id WHERE lp.section_id=?`).all(sectionId),qc=db.prepare(`SELECT COUNT(*) attempts,SUM(CASE WHEN attempt_state='completed' THEN 1 ELSE 0 END) completed,SUM(CASE WHEN attempt_state='declined' THEN 1 ELSE 0 END) declined FROM quick_check_attempts`).get(),answers=db.prepare(`SELECT qi.prompt,COUNT(ra.response_attempt_id) responses,SUM(ra.correctness) correct FROM question_items qi LEFT JOIN response_attempts ra ON qi.question_id=ra.question_id GROUP BY qi.question_id ORDER BY qi.question_id`).all(),writing=db.prepare(`SELECT COUNT(*) submitted FROM writing_drafts WHERE section_id=? AND draft_status='submitted'`).get(sectionId),confidence=db.prepare(`SELECT confidence_level,COUNT(*) count FROM reflection_responses WHERE prompt_id='confidence' GROUP BY confidence_level`).all(),support=db.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN support_state='resolved' THEN 1 ELSE 0 END) resolved,SUM(CASE WHEN support_state='escalated' THEN 1 ELSE 0 END) escalated FROM support_paths`).get();return send(res,200,{section:'COMP101-A',learners,quick_check:qc,questions:answers,writing,confidence,support,event_count:db.prepare(`SELECT COUNT(*) c FROM events`).get().c})}
  if(url.pathname==='/api/research/events'&&req.method==='GET'){const rows=db.prepare(`SELECT event_name,timestamp_utc_original,journey_id,activity_instance_id,sequence_number,payload FROM events ORDER BY timestamp_utc_original,sequence_number`).all().map(r=>({...r,payload:JSON.parse(r.payload)}));return send(res,200,{events:rows})}
  if(url.pathname.startsWith('/api/'))return send(res,404,{error:'Not found'});
  let fp=url.pathname==='/'?path.join(PUBLIC,'index.html'):path.join(PUBLIC,url.pathname);if(!fp.startsWith(PUBLIC))return send(res,403,'Forbidden','text/plain');if(!fs.existsSync(fp)||fs.statSync(fp).isDirectory())fp=path.join(PUBLIC,'index.html');const ext=path.extname(fp),types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','Cache-Control':ext==='.html'?'no-cache':'public, max-age=3600'});res.end(fs.readFileSync(fp));
}catch(err){console.error(err);send(res,500,{error:'Server error',detail:String(err.message||err)})}});
const port=process.env.PORT||4173;server.listen(port,()=>console.log(`Prototype 0.6 Stage 5B Bookmark and Unified Help running at http://localhost:${port}`));
