const {spawn}=require('child_process');
const root=__dirname;
const proc=spawn(process.execPath,['server.js'],{cwd:root,stdio:['ignore','pipe','pipe']});
let ready=false;
const post=async(url,body={})=>{const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(`${r.status} ${url}: ${await r.text()}`);return r};
proc.stdout.on('data',async d=>{const s=String(d);process.stdout.write(s);if(ready||!s.includes('running'))return;ready=true;try{
  let r=await fetch('http://localhost:4173/api/health');console.log('health',await r.json());
  r=await fetch('http://localhost:4173/api/me/home');console.log('home',(await r.json()).journey_state);
  r=await post('http://localhost:4173/api/journeys/start');let st=await r.json();
  r=await fetch('http://localhost:4173/api/activities/'+st.current_activity_instance_id);let act=await r.json();console.log('baseline',act.activity_type,act.content.phase);
  const baseline='Starting university will give me new opportunities, but I expect time management to be a challenge. I will need to balance classes, assignments, and daily responsibilities while learning how university study works. This matters because poor time management could make it difficult to complete work carefully and on time. I hope to build routines that help me plan ahead and ask for support when I need it.';
  r=await post(`http://localhost:4173/api/writing/${act.activity_instance_id}/submit`,{text:baseline,source_mode:'typed',baseline_confidence:'A little comfortable'});let br=await r.json();if(br.feedback.length!==0)throw new Error('Baseline should not generate feedback');
  r=await post(`http://localhost:4173/api/writing/${act.activity_instance_id}/continue`);let next=await r.json();
  r=await fetch('http://localhost:4173/api/activities/'+next.next_activity_instance_id);act=await r.json();console.log('stack',act.stack.panels.length);
  r=await post('http://localhost:4173/api/support/start',{activity_instance_id:act.activity_instance_id,trigger_type:'learner_requested',concept_id:'concept-audience'});let sup=await r.json();console.log('support',sup.path.support_state,sup.units.length);
  r=await post(`http://localhost:4173/api/support/${sup.path.support_path_id}/respond`,{response:'another'});sup=await r.json();if(sup.path.current_step!==2)throw new Error('Support path did not advance');
  r=await post(`http://localhost:4173/api/support/${sup.path.support_path_id}/respond`,{response:'got_it'});sup=await r.json();if(sup.path.support_state!=='resolved')throw new Error('Support path did not resolve');
  for(const p of act.stack.panels)await post(`http://localhost:4173/api/activities/${act.activity_instance_id}/panel`,{panel_id:p.panel_id});
  r=await post(`http://localhost:4173/api/activities/${act.activity_instance_id}/complete`);next=await r.json();
  r=await fetch('http://localhost:4173/api/activities/'+next.next_activity_instance_id);act=await r.json();console.log('quickcheck',act.quick_check.questions.length);
  await post(`http://localhost:4173/api/quick-checks/${act.activity_instance_id}/accept`);
  for(const q of act.quick_check.questions){r=await post(`http://localhost:4173/api/quick-checks/${act.activity_instance_id}/responses`,{question_id:q.question_id,response:q.expected_response});next=await r.json()}
  r=await fetch('http://localhost:4173/api/activities/'+next.next_activity_instance_id);act=await r.json();console.log('reading',act.content.title);
  await post(`http://localhost:4173/api/activities/${act.activity_instance_id}/reading-start`);
  r=await post(`http://localhost:4173/api/activities/${act.activity_instance_id}/complete`);next=await r.json();
  r=await fetch('http://localhost:4173/api/activities/'+next.next_activity_instance_id);act=await r.json();console.log('writing',act.activity_type,act.content.title,!!act.writing.draft);
  const para='Universities should offer flexible digital-skills support rather than requiring every student to complete the same course. The reading explains that students arrive with very different levels of experience. Some already know how to use academic software and evaluate online information, while others need more guidance. A flexible system could give all students a short introduction and then provide additional support to those who need it. This approach would avoid wasting time for students who already have strong skills while still helping students who need more practice become confident and independent learners.';
  r=await post(`http://localhost:4173/api/writing/${act.activity_instance_id}/submit`,{text:para,source_mode:'typed'});let wr=await r.json();console.log('feedback',wr.feedback.length);if(!wr.feedback.length)throw new Error('Application writing should generate feedback');
  r=await post(`http://localhost:4173/api/writing/${act.activity_instance_id}/continue`);next=await r.json();
  r=await fetch('http://localhost:4173/api/activities/'+next.next_activity_instance_id);act=await r.json();console.log('reflection',act.activity_type);
  r=await post(`http://localhost:4173/api/reflections/${act.activity_instance_id}/submit`,{responses:{audience_learning:'Audience affects the choices a writer makes.',audience_change:'A writer may change tone and detail for different readers.'},confidence:'Mostly confident'});next=await r.json();
  r=await fetch('http://localhost:4173/api/activities/'+next.next_activity_instance_id);act=await r.json();console.log('completion',act.activity_type);
  await post('http://localhost:4173/api/week1/complete',{action:'done'});
  r=await fetch('http://localhost:4173/api/me/home');const h=await r.json();console.log('final home',h.journey_state);
  r=await fetch('http://localhost:4173/api/me/learning');const p=await r.json();console.log('profile',p.week1.progress_state,p.writing.word_count);
  r=await fetch('http://localhost:4173/api/research/events');console.log('events',(await r.json()).events.length);
  if(h.journey_state!=='completed'||p.week1.progress_state!=='completed')throw new Error('Completion state failed');
  console.log('SMOKE TEST PASS');
}catch(e){console.error('SMOKE TEST FAIL',e);process.exitCode=1}finally{proc.kill()}});
proc.stderr.on('data',d=>process.stderr.write(d));
setTimeout(()=>{if(!ready){console.error('Server did not start');proc.kill();process.exit(1)}},4000);
